# Generated by Django 2.2 on 2019-10-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191002_0925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issue',
            new_name='Tracker',
        ),
    ]
